### PR TITLE
QMake: Ensure that assets.rcc is created when missing

### PR DESCRIPTION
**Pull request by akien-mga**
Note: The relevant change here is the addition of the `output` path.
The rest is cosmetic.

### CODE REVIEW

**Comment by larpon** [comment]
Argh - sorry I didn't see this until I fixed #7 - It'd be awesome if you could merge your changes

**Comment by akien-mga** [comment]
Sure, it's now rebased.

**Comment by akien-mga** [comment]
Hm it's still not enough to get the .rcc file generated in all cases, I'll look into it some more.

**Comment by akien-mga** [comment]
Ah, it does work but running `qmake` in the root folder does not generate the Makefile in the `App` folder apparently.

It looks like the SUBDIRS template you're using implies that one should run `qmake -r`: https://wiki.qt.io/SUBDIRS_-_handling_dependencies#Background_on_Windows_Build_Systems

With that switch it works, adding to the README.

**Comment by akien-mga** [comment]
I've tested the fix for #7, it works great :) I've adapted the instructions though as it referenced non standard paths.

**Comment by MCMic** [comment]
I’m not sure why but it does not seem to work for me I still get the assets is up to date message instead of building assets.rcc.

**Comment by larpon** [comment]
@akien-mga - great news!
@MCMic - make sure you remove any `.qmake.stash` or `.qmake.cache` files if you're rebuilding from previous checkouts (`.qmake.stash` is the root of much head scratching)

**Comment by MCMic** [comment]
Yeah I’m deleting the folder and starting again from the zip of the last commit each time but I still get assets is up to date message. What is supposed to change with these commits? The name of the target?

**Comment by larpon** [comment]
Hmm...
The commits are supposed to give you the game's assets as a separate file `assets.rcc` in either your build directory or what you specify in the `ASSETS_DIR` qmake variable. The game binary should have the same name as previously - but it should be smaller because the assets are not compiled in any more (to fix your original issue #3)

**Comment by larpon** [comment]
It sounds like your build directory has files from previous builds that `qmake` think hasn't changed or something. That's why I'm suggesting you remove the output directory _completely_ (not just it's contents as it has the hidden `.qmake.*` files I've mentioned) :)

**Comment by MCMic** [comment]
I delete the whole folder each time.
If I change "assetsTarget.target = assets" for "assetsTarget.target = assetsrcc" then make assetsrcc -C App works as it should.

**Comment by larpon** [comment]
That's super weird. What versions of `qmake` and `make` are you running? And where in the project tree are you executing `make`?

Could you try a shadow build and see if the problem persists:
```
cd /tmp
mkdir dabuild
cd dabuild
qmake -r /abs/path/to/DeadAscend.pro <options>
make assets -C App
make
make install
```

**Comment by MCMic** [comment]
Hum actually when I try from the master by hand it does work.
But using https://github.com/Larpon/DeadAscend/archive/master.zip as source for my PKGBUILD does not, I don’t get what is different…

**Comment by larpon** [comment]
That's super odd - github creates those zips automatically

**Comment by akien-mga** [comment]
At any rate, renaming the target to something other than `assets` (and thus prevent the confusion with the `assets` folder) should solve it in all cases. `make` tries to determine if the target needs rebuilding, and if the target is a file or folder with no modified dependencies, it won't be rebuilt.

**Pull request merged**
